# Generated by Django 2.2.13 on 2021-01-09 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendedEmails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('confirm_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Students')),
            ],
        ),
        migrations.AlterField(
            model_name='thesis',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
